remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Erin Webreck
description: T&T sample site for intro

nav:
  - title: Home
    url: /
  - title: Experience
    url: /experience
  - title: Education
    url: /education

