remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Erin Webreck
description: 

nav:

  - title: Experience
    url: /experience
  - title: Education
    url: /education
  - title: Certifications/Licenses
    url: /certifications
  - title: Teaching
    url: /teaching

logo: /assets/images/logo.jpeg

